# Ticket system configuration

# Directory settings
tickets_dir: "tickets"

# Git settings
default_branch: "main"
branch_prefix: "feature/"
repository: "origin"
auto_push: true
delete_remote_on_close: true

# Success messages
start_success_message: "Please review the ticket content in `current-ticket.md` and make any necessary adjustments before beginning work."
close_success_message: ""

# Ticket template
default_content: |
  # Ticket Overview
  
  Write the overview and tasks for this ticket here.
  

  ## Tasks
  
  - [ ] Task 1
  - [ ] Task 2
  ...
  - [ ] Run tests before closing and pass all tests (No exceptions)
  - [ ] Get developer approval before closing
  

  ## Notes
  
  Additional notes or requirements.
