# Ticket system configuration

# Directory settings
tickets_dir: "tickets"

# Git settings
default_branch: "main"
branch_prefix: "feature/"
repository: "origin"
auto_push: true

# Ticket template
default_content: |
  # Ticket Overview
  
  Write the overview and tasks for this ticket here.
  
  
  ## Tasks
  
  - [ ] Task 1
  - [ ] Task 2
  ...
  - [ ] Get developer approval before closing
  

  ## Notes
  
  Additional notes or requirements.
