name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup environment
      run: |
        git config --global user.name "Test User"
        git config --global user.email "test@example.com"
        if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
        fi
    
    - name: Make scripts executable
      run: |
        chmod +x ./build.sh ./test-all.sh
        chmod +x ./test/*.sh
        chmod +x ./yaml-sh/*.sh
    
    - name: Build ticket.sh
      run: ./build.sh
      
    - name: Verify build
      run: |
        test -f ticket.sh
        test -x ticket.sh
        
    - name: Test help command
      run: |
        ./ticket.sh --help
        ./ticket.sh help
        
    - name: Test with no arguments
      run: ./ticket.sh
      
    - name: Run all tests
      run: ./test-all.sh
      timeout-minutes: 10
        
  yaml-sh-test:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        
    steps:
    - uses: actions/checkout@v4
    
    - name: Test yaml-sh
      run: |
        cd yaml-sh
        ./test.sh
        
  shellcheck:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install shellcheck
      run: sudo apt-get update && sudo apt-get install -y shellcheck
      
    - name: Check shell scripts
      run: |
        # Run shellcheck with error severity to allow warnings
        shellcheck --severity=error build.sh
        shellcheck --severity=error src/ticket.sh
        shellcheck --severity=error lib/*.sh
        shellcheck --severity=error yaml-sh/yaml-sh.sh
        # Test scripts are allowed to have more warnings
        shellcheck --severity=error test-all.sh
        shellcheck --severity=error yaml-sh/test.sh